### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by haowayne** [KimAlittleStar/vscode_c_demo#1]
师傅您好，我创建了一个文件夹SM3，其中.vscode目录下的文件以及makefile文件均使用您的配置。并且修改了mingw64相关的路径。但我在命令行运行mingw32-make.exe的时候会报错，可以麻烦解答下吗？谢谢

![image](https://user-images.githubusercontent.com/22594554/118099492-e3875500-b407-11eb-9172-fced256e6b0b.png)

**Comment by KimAlittleStar** [comment]
上面报错的原因是因为你没有grep.exe软件
如果你已经安装了git，那么你需要把你当前项目的默认命令行更换成git-bash，目录好像是 <git-dir>/bin/bash.exe
如果你没有安装git，那么你需要去下载一个压缩包，Windows for bash（好像是叫这么个名字），然后会得到 grep，ls等等一系列可执行文件，添加这个路径进入你的path环境变量，关闭vscode再尝试应该就可以了

**Comment by KimAlittleStar** [comment]
上面报错的原因是因为你没有grep.exe软件
如果你已经安装了git，那么你需要把你当前项目的默认命令行更换成git-bash，目录好像是 /bin/bash.exe
如果你没有安装git，那么你需要去下载一个压缩包，Windows Build Tools，然后会得到 grep，ls等等一系列可执行文件，添加这个路径进入你的path环境变量，关闭vscode再尝试应该就可以了 附件为 压缩包




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimAlittleStar/vscode_c_demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 下午4:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[KimAlittleStar/vscode_c_demo] 无法运行 (#1)





 
师傅您好，我创建了一个文件夹SM3，其中.vscode目录下的文件以及makefile文件均使用您的配置。并且修改了mingw64相关的路径。但我在命令行运行mingw32-make.exe的时候会报错，可以麻烦解答下吗？谢谢

**Comment by KimAlittleStar** [comment]
> 师傅您好，我创建了一个文件夹SM3，其中.vscode目录下的文件以及makefile文件均使用您的配置。并且修改了mingw64相关的路径。但我在命令行运行mingw32-make.exe的时候会报错，可以麻烦解答下吗？谢谢
> 
> ![image](https://user-images.githubusercontent.com/22594554/118099492-e3875500-b407-11eb-9172-fced256e6b0b.png)



> 劳斯·莫里，基特·米斯姆3.v代码·哈德尔·莫德·莫西特·莫西德温明w64德普有名副使的明w32使.exe的天金兑换，《无国大非》的《无名小子》？
> 
> ![image](https://user-images.githubusercontent.com/22594554/118099492-e3875500-b407-11eb-9172-fced256e6b0b.png)
